<template>
  <div>
    <h2>Условия оплаты:</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, cupiditate fuga corrupti quasi, explicabo deserunt porro amet adipisci cumque, ipsa sint laborum quisquam delectus molestiae dignissimos itaque obcaecati vero cum deleniti consequuntur architecto voluptate! Accusamus similique eveniet, atque, alias cum provident vitae delectus nulla natus aliquid quidem cupiditate quam? Obcaecati laudantium ex voluptatum commodi nam culpa placeat asperiores itaque repudiandae nesciunt blanditiis officia quia esse similique dolorem veniam omnis nulla molestiae incidunt nisi praesentium aliquid, est dolorum. Neque possimus unde iure modi vero consectetur commodi, earum beatae reiciendis dolore nam impedit, eaque rem harum quis facere sint voluptates, ab quos eveniet nobis optio! Amet dicta cupiditate ut odit velit dolore perferendis, tempora ipsum provident saepe ipsam deserunt cumque natus corrupti iure accusantium? Labore exercitationem fuga, obcaecati, vero possimus deserunt eligendi repudiandae placeat voluptas distinctio maiores sit aut sapiente ut impedit nulla neque nostrum adipisci laborum! Placeat magnam totam, praesentium incidunt reiciendis quaerat. Cumque voluptatibus non a sint molestiae reprehenderit excepturi? Iure sint nostrum necessitatibus et distinctio enim alias, optio commodi quaerat laboriosam aut numquam corrupti impedit aperiam accusantium molestiae ipsam eaque sit quia ratione recusandae quas praesentium placeat explicabo. Nulla ipsum enim qui consequatur quod dolores obcaecati soluta culpa doloribus!</p>
    <h2>Доставка товара</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita, eligendi repellat dignissimos perferendis dicta fuga voluptatem rem officia quasi? Culpa facilis harum quos consequatur aspernatur et? Nulla debitis molestias error in itaque quisquam, reprehenderit deserunt quia porro ipsa dolore voluptatibus id iure suscipit. Maxime ipsam dignissimos quae quia atque rem nisi non accusamus, suscipit, velit similique autem fugit illum, perferendis incidunt maiores vel fugiat? Natus, sequi, maiores aliquam quidem nobis beatae magni vel quo temporibus facere soluta dolore totam accusamus architecto nulla veniam cupiditate doloribus perferendis suscipit quaerat consectetur? Qui dignissimos quis magni, debitis possimus natus ipsa hic error dolorem, tempore assumenda vel ea suscipit delectus culpa fugiat? Culpa cumque laboriosam corporis vel, necessitatibus numquam at ipsam aperiam, reprehenderit modi impedit doloremque tempora perferendis. Eius saepe sit fugit, hic quam quis quae ipsam deserunt dolore provident a ab accusantium sequi exercitationem eveniet esse asperiores cum beatae consequatur iusto maiores porro.</p>
  </div>
</template>

<script>
export default {};
</script>